### ISSUE TITLE
GAF downloads show wrong date

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/helpdesk#107]
http://geneontology.org/page/download-go-annotations 

The 'submission date' column info does not match the GAF file date.  I looked at SGD's and MGI's GAFs, both show this month in the headers.  GO page makes them appear over 6 months out of date (from September 2017). 

Does not appear the 'submission date' has picked up anything since last October.

The same files are available at  http://www.geneontology.org/gene-associations/ with the right date, although this directory is difficult to find. (is it intentionally hidden?)

Thanks

**Comment by kltm** [comment]
@suzialeksander 

There should be a ticket around here for this...ah: https://github.com/geneontology/go-site/issues/542

Essentially, the old metadata pipeline to drive that page borked out a few months ago. Rather than spend the time reconstituting it, we've been doubling down on getting the new pipeline done: https://github.com/orgs/geneontology/projects/11

What we have for the new downloads page and browser are here, with their tickets ready to be "cleared" once we are absolutely happy with the GAF checks and contents (re: last week's discovery about headers).

http://current.geneontology.org/
http://current.geneontology.org/products/pages/downloads.html
