### ISSUE TITLE
What properties are used to link genes to processes and components?

### ISSUE THREAD

**Issue by diatomsRcool** [geneontology/helpdesk#125]
I'm going to ask a really stupid question. I've been all through the documentation and I just want to confirm.

Genes are linked to processes via the 'regulates' property, right? And linked to components via 'part_of'? There's a lot of documentation and nothing every actually comes out and says it.

**Comment by kltm** [comment]
@diatomsRcool (and the are),

That is actually a good question and one that we've been talking about make more explicit recently. I am assuming that the domain of this question is the data that you're looking at in the GAF files, AmiGO, or similar?

@cmungall Would you have any pointers for the current discussion for GAF 2.1.1 and term/gene relations?

**Comment by cmungall** [comment]
The default relations are described in the GAF docs: http://www.geneontology.org/page/gene-product-association-data-gpad-format

So for BP, it is 

We are planning more detailed documentation on this, I'll show some of our internal docs since I know @diatomsRcool knows ontologies and is a RO contributor

In GPAD there are a wider range of relationships (all in RO):

http://wiki.geneontology.org/index.php/Category:Gene_Product_to_Term_Relations

This allows us to distinguish when a gene is involved in apoptosis vs acting upstream vs don't know.

The most granular level of modeling is the GO-CAM - you can find some examples in the wiki pages above

**Comment by suzialeksander** [comment]
Hi @diatomsRcool, 

Is that a sufficient answer? Do you have any more questions about this? If not, I will close this ticket as resolved. Thanks!

**Comment by suzialeksander** [comment]
Closing as resolved.
