### ISSUE TITLE
Mouse annotation file

### ISSUE THREAD

**Issue by capricy** [geneontology/helpdesk#13]
Dear GO Team,

Could you please let me know what version of Mouse genome the current annotation (24426 records) is corresponding to?

Thanks.

Kind regards,

C.

**Comment by kltm** [comment]
@hdrabkin Is this something that you'd be able to answer?

**Comment by hdrabkin** [comment]
The Mouse Genome Informatics system (MGI) is the official source of GO annotation for mouse genes
The current mouse genome build is GRCm38. 
Our (MGI) GO annotations don't normally change because of changes in builds unless
1. a "gene" becomes a pseudogene, or other non-gene type marker; MGI annotates to only marker type gene
2. If an annotation is imported from GOA, who muse UniProt identifiers;  the UniProt ID must map to an MGI gene; A new build might cause a link to no longer be valid; 
3. Orthology pipeline: we use data from HGNC and HomoloGene, If there are changes here, certain annotations made by orthology may be removed.

Further info might be better supplied by using the MGI help desk
http://www.informatics.jax.org/mgihome/support/mgi_inbox.shtml
