### ISSUE TITLE
Access to GO MySQL database

### ISSUE THREAD

**Issue by dminkley** [geneontology/helpdesk#140]
Hello,

Our program, GO Trimming (http://lucy.ceh.uvic.ca/go_trimming/cbr_go_trimming.py), currently uses the MySQL database mirror to access the ontology in order to perform certain GO 'pruning' tasks.  We had been using mysql.ebi.ac.uk, port 4085 to connect, but this appears to no longer be working.  I tried both the EBI and BBOP 'go_latest' mirrors listed on this page, and wasn't able to connect to those either:
http://www.geneontology.org/page/go-mysql-database-guide#mirrors

Looking around the helpdesk tickets here, it looks like GO has been planning a move away from a MySQL-based structure for a little while now (to Blazegraph?).  Admittedly, I haven't been doing much GO work in the past year or two, and only became aware of the issue when a user sent us an email.  I'd like to update our software so that it will continue to work with the current form of the GO database.  To this end I have a couple questions:

- Is support for MySQL mirrors/versions of the database officially ended?
- What is the best resource to learn more about the move and the new system?

Thanks!

-David

**Comment by kltm** [comment]
@dminkley 

Hm yes. Due to a recent security issue, IP addresses for the Berkeley mirrors now need to be part of a whitelist. As the GOOSE interface is still up, this was considered to be a fairly minor issue at the time. Our recommendation would be to run a local mirror for your application--that's certainly the best guarantee of uninterrupted service.
The legacy systems (mainly the pipeline and delivery of the MySQL, mentioned in #4 ) are being decommissioned as they fail or no longer become viable. The new system is in various states of readiness, with the rdf endpoint (rdf.geneontology.org) being largely ready to use, with the peripheral query interface and documentation still being built up.
A couple of good places to start with the new system would be:

https://github.com/geneontology/go-site/blob/master/graphstore/triplestore_info.md
https://github.com/geneontology/go-graphstore/wiki/Example-queries

We're currently working on more documentation and introductions. Our apologies for the awkward transition period.
