### ISSUE TITLE
Some pages producing 404 errors

### ISSUE THREAD

**Issue by jweiser** [geneontology/helpdesk#179]
Hello,

I was trying to access the instructions for checking out the GO SVN repository and I am getting back a 404 page:
http://geneontology.org/page/svn-help

I was able to access the instructions of the older page here:
https://web.archive.org/web/20171106124608/http://geneontology.org/page/svn-help but I'd like to make sure I am using the most up to date docs.

I'd very much like to join the GO mailing list as well, but the mailing list page also is returning a 404:
http://geneontology.org/page/go-mailing-lists

Thanks for your help!

**Comment by suzialeksander** [comment]
Hi @jweiser, 

We just released a new website and have eliminated many pages that were unused, out of date, or confusing.  It seems we've overlooked that page and will add it back to the new site, thank you for letting us know about this.  

Can you give me which URL you found the information linking to mailing list? You can certainly sign up for our go-consortium mailing list, but our GitHub repos are much more active.  I've emailed you a link to sign up for the list.

**Comment by jweiser** [comment]
Hi @suzialeksander,

Great, thanks for your quick response!

Sure, the URL with the mailing list links was this page: http://help.geneontology.org/

The two links are in the last paragraph with the text 'mailing lists'.

I'm not sure I received the link to sign up for the mailing list.  Could you please re-send it to joel.weiser@oicr.on.ca?
 
Thanks!

**Comment by noedelta** [comment]
Related to the same topic. 

Could you help me to point me out which one is the replacement for this
file in the new site: http://geneontology.org/ontology/go-ontology-edit.obo because I am not sure if I should replace it with http://geneontology.org/ontology/go-basic.obo or http://snapshot.geneontology.org/ontology/go.obo (we download the obo file in our IntAct and ComplexPortal release)

Kind regards

**Comment by suzialeksander** [comment]
@jweiser, the SVN instructions are now available under the Downloads section (http://geneontology.org/docs/downloads/) under the new address http://geneontology.org/docs/SVN-access/, but the old address you have will redirect in case it's bookmarked by any of our users.  

We're updating the help page with specific links, thank you for finding those and letting us know about the broken links.  

If you have any other issues, feel free to open a new ticket! Thank you for contacting GO.

**Comment by suzialeksander** [comment]
@noedelta I've moved your issue to a new ticket: https://github.com/geneontology/helpdesk/issues/184

**Comment by suzialeksander** [comment]
@noedelta Please look at https://github.com/geneontology/helpdesk/issues/184 for the solution-  http://purl.obolibrary.org/obo/go/go-basic.obo.  I'm not entirely sure that tagging you was effective (as your username didn't autocomplete on that ticket), so just making sure you know your issue was solved. Again, apologies for the sudden transition.
