### ISSUE TITLE
how to get all Go terms that in a specific level?

### ISSUE THREAD

**Issue by Dongxn** [geneontology/helpdesk#18]
Hi, I am doing GO analysis and I am curious about - if there are any files that contain a list of GO terms in a specific level, for example level 3? Thank you

**Comment by kltm** [comment]
@Dongxn,

For an analysis, you may want to reconsider using GO "levels", as there really isn't any such thing due to multiple paths through the graph and granularity of terms.
For a little more discussion, as well as a possible path forward if you choose to go that way, please the the FAQ:
 http://geneontology.org/faq/how-can-i-calculate-level-go-term

kltm
