### ISSUE TITLE
GOA annotations no longer available for download?

### ISSUE THREAD

**Issue by keseler** [geneontology/helpdesk#185]
It seems that the downloads page on the new GO website no longer has the full GOA annotation file available for download.  Was that intended?
Cheers,
Ingrid

**Comment by kltm** [comment]
@keseler 

Our apologies--we've been having a few hiccups with our root domain transition.
Could you let us know what the expected URL for your file was? I do believe that we still have the full file available at (for example): http://current.geneontology.org/annotations/goa_uniprot_all.gaf.gz

**Comment by keseler** [comment]
The person who usually downloads this file used the ftp site,
ftp://ftp.geneontology.org/pub/go/gene-associations/submission/
This page is accessible, and there is currently a goa_uniprot_all.gaf.gz file there, but it has a date of 1/12/18.  I'm not planning to start downloading it...  From what I recall, the list of downloadable annotation files at http://current.geneontology.org/products/pages/downloads.html used to have an entry for the UniProt-all dataset (and perhaps one filtered for annotations with experimental evidence, I think).

The Jan. 16 email from GOA announcing their latest release contained this URL:
http://geneontology.org/page/download-go-annotations

**Comment by davidbio** [comment]
@kltm 
Just curious.
http://current.geneontology.org/annotations/goa_uniprot_all.gaf.gz
This file has not been updated since Feb. 13th, 2019.
Is there no new version yet or is this another issue?
http://current.geneontology.org/products/pages/downloads.html
All files on this page have been updated in March, but the above mentioned file is not even listed, though it would make sense to me.

**Comment by alexsign** [comment]
@davidbio there will be no March release for GOA because it's in sync with UniProt public releases. Due to technical reasons next UniProt public release will be on April 10th.

**Comment by davidbio** [comment]
@alexsign 
Good to know.
Thank you.

**Comment by suzialeksander** [comment]
OK, it looks like two files are accessible at http://current.geneontology.org/annotations/index.html but still not http://current.geneontology.org/products/pages/downloads.html : 
*    goa_uniprot_all_noiea.gaf.gz
 *   goa_uniprot_all.gaf.gz

I don't think this was intentional, apologies to @davidbio and @keseler for the confusion.  Looking into what happened to them, but for now please grab them at http://current.geneontology.org/annotations/index.html. 

Also, @keseler, we are making plans to retire the FTP site, no definite date as of right now though.  We will try and notify as many users as possible before this switch occurs.

**Comment by davidbio** [comment]
Thanks for getting back on this.
The goa_uniprot_all.gaf.gz file is still out of date:

```bash
# curl http://current.geneontology.org/annotations/goa_uniprot_all.gaf.gz | zcat | head -n7
!gaf-version: 2.1
!
!This file contains all GO annotations and gene product information for proteins in the UniProt KnowledgeBase (UniProtKB),
!ComplexPortal protein complexes, and RNAcentral identifiers.
!
!Generated: 2019-02-13 17:01 
!GO-version: http://purl.obolibrary.org/obo/go/releases/2019-02-07/extensions/go-plus.owl
```

I hope @alexsign's information is still valid and an update is scheduled for April?

**Comment by alexsign** [comment]
yes, it is. The GOA release is on April 10th. Ao far I see no reason for delay.

**Comment by suzialeksander** [comment]
@keseler, we recently made an announcement about retiring gp2protein files via the GO-Friends mailing list.  We plan to send out other such announcements via the GO-Friends mailing list, as well as Twitter and FaceBook, and hopefully this will help reach more users.  If you did not receive the GO-Friends announcement or there is someone else in your group that needs to be on this list, please let us know and we can update the mailing list.
