### ISSUE TITLE
Best way to get GO-term name from gene name or description 

### ISSUE THREAD

**Issue by Ella-Bowles** [geneontology/helpdesk#198]
Hello,

I have short read data from walleye that I am trying to get functional information for. I have blasted the sequences and gotten information like the following
"sp|D3K0R6|AT2B4_BOVIN Plasma membrane calcium-transporting ATPa...  39.7    7e-05
sp|O75864|PPR37_HUMAN Protein phosphatase 1 regulatory subunit ...  36.6    8e-04
sp|P23220|AT2B1_PIG Plasma membrane calcium-transporting ATPase...  36.6    8e-04"

From this, I would like to be able to get the GO-term name, basically so that I have a functional classification for the genes. I'm hoping to be able to produce something like the following
![image](https://user-images.githubusercontent.com/41387926/54768982-bbf52300-4bd6-11e9-9df7-79354b0be7df.png) 
without the gene start and finish info, since my reads were not reference-aligned.

I have tried a lot of different things to do this. I think I've figured out a way to do it manually, but want to check that I am interpreting correctly and also ask if there is a way for me to do this in batch? What I want is to get the functional information searched over many species, so some "consensus" of sorts, because there is no genome for walleye as yet, and the next closest thing is pretty far way. Basically, I want to look for the most accurate general function to match. 

I think that http://geneontology.org/ is the place to do this. I have put in some functional information"Glutamate receptor ionotropic, delta-1 OS=R" into the search box, checked ontology, and came up with what is listed here http://amigo.geneontology.org/amigo/search/ontology?q=Glutamate+receptor+ionotropic%2C+delta-1+OS%3DR&searchtype=ontology. If I look down the list, the biological process that is listed is 

(R)-carnitine transmembrane transport | The process in which (R)-carnitine is transported across a membrane. | biological_process | GO
-- | -- | -- | --

Would the R-carnitine transmembrane transport be the GO-term?

If it is, how can I submit these queries in batch, and just filter for the biological processes?

With many thanks,
Ella

**Comment by suzialeksander** [comment]
Hi @Ella-Bowles, thanks for writing in to GO.  

It sounds like the search you did on GO wasn't really what you wanted to do.  Searching the Ontology brings back Gene Ontology terms that match/hit your search criteria; the R in your search term <code>OS=R</code> looks to have hit on the R in the term <code>(R)</code>-carnitine transmembrane transport- this is why the R is highlighted in green on AmiGO.  The Ontology search was meant to help users find GO terms: if a user wanted to see a definition or the GO ID (the number associated with the term)  of _prenyl alcohol phosphotransferase_, the search would help them identify the term [prenol kinase activity](http://amigo.geneontology.org/amigo/term/GO:0052673), which is a synonym for exactly what they searched for.  A Gene Product search retrieves all  genes/gene products with that name- so [BRCA1](http://amigo.geneontology.org/amigo/search/bioentity?q=BRCA1&searchtype=geneproduct) brings back the expected human protein, plus _Arabidopsis_, opossum, algae, etc. that share the name.

1. One solution would be to submit your sequences to NCBI or UniProt.  Once the sequences are in the system, Interpro2GO will automatically create IEAs (electronic annotations, as opposed to annotations derived from experimental data) that meet GO's quality requirements and would be available as an official GO product.

2. The above isn't always reasonable and is slow, of course, so PANTHER is an excellent alternative.  [PANTHER](http://www.pantherdb.org/), which supports the backend of the GO, provides the list of the species found in the right side of GO website. Besides the 110+ genomes listed there, [PANTHER supports another 800+ genomes](ftp://ftp.pantherdb.org/generic_mapping/) from the Reference Proteome project for users to generate GO annotations. 

   Since I think your organism is not one of the nearly 1000 genomes supported in PANTHER, there are two options:

   * The first option is to contact the [Reference Proteome project](https://www.ebi.ac.uk/reference_proteomes) and work with them to incorporate the genome in their project. Once that is done, you can use the regular process to generate the GO annotation file. [Again, this may be slow or unreasonable in your situation.]

   * The second option is to score your genomes against the PANTHER HMM library. Read our [Nature protocol paper](https://www.nature.com/articles/nprot.2013.092), and find the details in Box 2:

![Box 2 of the PANTHER Nature protocol paper](https://media.nature.com/lw685/nature-assets/nprot/journal/v8/n8/images/nprot.2013.092-I2.gif)

3. Alternatively, have you considered using Blast2GO? It's not a tool developed by GO, so we can't help you use it, but it is also meant for your situation- assigning GOs to novel sequences.  I believe you can even use the tool for free if you're a non-profit research organization. 


Please let me know if this doesn't answer your question, or if there are any other GO-related questions you may have!

**Comment by Ella-Bowles** [comment]
Is this "carnitine transmembrane transport" not the GO-term?

**Comment by suzialeksander** [comment]
Hi @Ella-Bowles, "Glutamate receptor ionotropic, delta-1 OS=R" is a protein name, but not necessarily  a useful indicator of the function.  As you can see from two of my favourite proteins- [Tiggy-winkle hedgehog protein](https://www.uniprot.org/uniprot/Q90419) and [Protein bag-of-marbles](https://www.uniprot.org/uniprot/P22745)- nomenclature standards vary and the name doesn't necessarily reflect the function.  Biologically, it's not safe to make inferences about a protein's function from just the name, and it's not safe to make assumptions based on a sequentially similar protein's name. 

So, _carnitine transmembrane transport_ is **a** GO term, but it almost certainly has nothing to do with your protein.  Since I think you're looking at the human GRID1 (protein name is "Glutamate receptor ionotropic, delta-1"), look at the GO terms for it here:

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q9ULK0

You'll see that _carnitine transmembrane transport_ is not annotated to Glutamate receptor ionotropic, delta-1.  This is why the hit on that GO term is simply because of the R (and that's why the R is highlighted in the AmiGO search).  

Does that make sense?

**Comment by Ella-Bowles** [comment]
Hello @suzialeksander , and yes! Thank you so much. I will try blast2GO and see if that works.

**Comment by suzialeksander** [comment]
Great.  Let us know if there's anything else GO-related we can help with!
