### ISSUE TITLE
GO for non-model unsequenced plants

### ISSUE THREAD

**Issue by jhashweta80** [geneontology/helpdesk#201]
I have a list of identified proteins from proteomics data of a plant, which is not listed in the species list. How can I perform GO annotation an GO enrichment analysis for that?

**Comment by suzialeksander** [comment]
Hi @jhashweta80, 
Thank you for contacting GO.  This question is [listed in our FAQ](geneontology.org/docs/faq#how-can-i-do-term-enrichment-analysis-for-a-species-that-is-not-present-in-the-list-from-amigo):
 Since I think your organism is not one of the nearly 1000 genomes supported in PANTHER, there are two options:

   * The first option is to contact the [Reference Proteome project](https://www.ebi.ac.uk/reference_proteomes) and work with them to incorporate the genome in their project. Once that is done, you can use the regular process to generate the GO annotation file. [This may be slow or unreasonable in your situation.]

   * The second option is to score your genomes against the PANTHER HMM library. Read our [Nature protocol paper](https://www.nature.com/articles/nprot.2013.092), and find the details in Box 2:

![Box 2 of the PANTHER Nature protocol paper](https://media.nature.com/lw685/nature-assets/nprot/journal/v8/n8/images/nprot.2013.092-I2.gif)


Hope this helps.  Let us know if you need any more information!
