### ISSUE TITLE
goa_human.gaf file reduced by 50K IBA annotations?

### ISSUE THREAD

**Issue by jrsjrs** [geneontology/helpdesk#206]
Hi, we download the human GO annotations from the GOC on a weekly basis and found that between 13 April and 18 April the file size was reduced by almost 40%.  Looking at the changes we found that the newer file(s) have more the 50,000 fewer IBA annotations than the previous file.  I tried to find any documentation on the GOC site that would explain the differences, without success.  I would contact GOA but it's my understanding that the PAINT annotations are coming (and actually are required to come) from the GOC.  Could you please help us understand the change?  Is it possible there's a problem with the file?  We will not remove the annotations from our database until we know that the reduction was intended, but if it was and those annotations are not valid, we would like to remove them from our db.

Thank you!

Jennifer Smith
Rat Genome Database

**Comment by kltm** [comment]
@jrsjrs To confirm, you'd be talking about this file?
http://current.geneontology.org/annotations/goa_human.gaf.gz
A new release was finalized on the 18th, so that could be the matching date of the discontinuity.
See: http://release.geneontology.org/ for current release dates.

For the actual data drop issue, I've started a proper item here: https://github.com/geneontology/go-site/issues/1061

**Comment by pgaudet** [comment]
This is now solved. Please reopen of you find otherwise. 

Thank you for reporting this. 

Best regards, Pascale
