### ISSUE TITLE
graph_path.txt explanations

### ISSUE THREAD

**Issue by capricy** [geneontology/helpdesk#208]
Hello, there,

I downloaded the graph_path.txt from the archive link:

http://archive.geneontology.org/full/

Can anyone explain what each column means?

Thanks.

Kind regards,

C.

**Comment by suzialeksander** [comment]
Hi @capricy,

Since we are no longer supporting the MySQL pipeline, these files have been archived. Unfortunately, that means we've also removed the help documentation that accompanied them.  You can still access it here: https://web.archive.org/web/20170214105433/http://geneontology.org/page/lead-database-schema#go-optimisations.table.graph-path

We apologise for any inconvenience this has caused.  We recommend you take a look at using our Blazegraph dumps for more recent data.  See the background on this issue: https://github.com/geneontology/helpdesk/issues/4 and [more in-depth information on our Gene Ontology Public Triple Store](https://github.com/geneontology/go-site/blob/master/graphstore/triplestore_info.md).

Please let us know if you still need more information.

**Comment by capricy** [comment]
Thank you very much for the useful information!

**Comment by suzialeksander** [comment]
I'm glad it was helpful.  Let us know if you need anything else.
