### ISSUE TITLE
Why are taxon checks not implemented for gorule-report?

### ISSUE THREAD

**Issue by hattrill** [geneontology/helpdesk#228]
Error reports used to be generated for taxon violations in the old Jenkins reports. I cannot see that GORULE:0000013 has been implemented in current reports:
http://current.geneontology.org/reports/gorule-report.html

and the GO rules on github say that this check is "legacy" https://github.com/geneontology/go-site/blob/master/metadata/rules/README.md
Taxon-appropriate annotation check

    id: GORULE:0000013
    status: legacy

What is going on here?

**Comment by kltm** [comment]
@pgaudet or @dougli1sqrd , Could you give a quick summary of the current state of the GO Rule and the taxon check (as present and roadmap)?

**Comment by dougli1sqrd** [comment]
Sure thing. So the current new(ish) data validation pipeline that replaces old Mike's Script we weren't able to do taxon checks (GORULE:0000013) in the line by line GAF checks that are used to produce the big report page. GORULE:0000013 was set to `legacy` since we still run the old checks with OWLTools (for example for FB: http://current.geneontology.org/reports/fb-report.html#otc). These violations don't show up on the gorule-report.html, but you can find them with the rest of the "GO_AR" rules. For example, aspgd has GORULE:0000013 violations: http://current.geneontology.org/reports/aspgd-report.html#otc (search for GO_AR:0000013). To reiterate, since these reports only exist right now in the older OWLTools report, we say that the rule is legacy and will not show up on the main gorule-report.html page.

But taxon checks _are_ in the works right now. Working with Jim Balhoff we are able to put the taxon checks in the current line by line GAF checks. Testing of the new taxon checks show that they seem to be working, but this is still in active development. This is nearing completion however, and you can expect to see taxon checks in the main report soon!

**Comment by hattrill** [comment]
Ok. Thanks for the summary!
