### ISSUE TITLE
Is pantherdb.org under maintenance?

### ISSUE THREAD

**Issue by dniessi** [geneontology/helpdesk#243]
I can't receive any results from pantherdb.org after submission of protein IDs at geneontology.org. This also occured last week. It simply does not seem to connect to the pantherdb.org website. I tried this with a list of IDs but also with a single entry (AATF_HUMAN). Pantherdb.org always gives a time-out error.
Thanks for looking into it.

**Comment by suzialeksander** [comment]
@dniessi PANTHER has their own support team.  You can contact the PANTHER team at pantherfeedback@yahoo.com. Please include "Panther feedback" in the subject line.

Please supply them with your country/IP and any other info they may need to recreate your issue (including the list you were trying to run).  I know there was an incident recently where certain countries were being blocked (servers are owned by the university system, not PANTHER directly) due to circumstances beyond the PANTHER team's control, but I am not sure if that has been resolved or perhaps there are new issues.  Please contact the PANTHER team for full details.

**Comment by dniessi** [comment]
Hi there, 
this makes a lot of sense. Probably our University has been blocked for some reason. Using a VPN with a different location to the outside allows for using Panther. 
Thanks and best regards
Dierk

**Comment by suzialeksander** [comment]
@dniessi, the database has been moved to an alternate server.  You may experience some issues in the next 2-3 hours while they are doing some maintenance, but if you experience any problems after that please let us know.
