### ISSUE TITLE
How many microbe species are included in GO annotation?  

### ISSUE THREAD

**Issue by ybdong919** [geneontology/helpdesk#247]
**Please describe your question, idea, or concern.**
I want to know How many microbe species are included in GO annotation?  How can I get a list of this.

**Comment by suzialeksander** [comment]
Hi @ybdong919, 

This is a bit tricky as what fits the definition of "microbe" can be debated.  If you really need the answer to this, I would start by reading our FAQ:
geneontology.org/docs/faq#how-do-i-annotate-a-novel-genome-with-go-annotations

So, if you find the genome in NCBI, you can assume it is or soon will have GO annotations.  You can then search for these in a GO browser by taxon; I would probably start with taxon:10239, taxon:2, taxon:2157, and I leave it to you to split eukaryotes.  Please also note that due to the nature of annotation, most microbes will only have IEAs and you will find more results in QuickGO: http://geneontology.org/docs/faq/#what-are-the-differences-between-the-data-available-in-amigo-and-those-on-quickgo
