### ISSUE TITLE
FCGR2B and positive phagocytosis regulation

### ISSUE THREAD

**Issue by juliethmurillosilva** [geneontology/helpdesk#250]
**Please describe your question, idea, or concern.**
Hello, I just wanted to know why FCGR2B is annotated in "Positive regulation of phagocytosis" and at the same time, negative regulation of the same process (that, by the way, makes more sense to be in this latter category ).

Thank you very much.

**Comment by suzialeksander** [comment]
Hi @juliethmurillosilva, 
Thanks for contacting us.  As you can see on http://geneontology.org/docs/faq/#can-a-single-gene-product-be-annotated-with-more-than-one-go-term, it is generally expected that some gene products have multiple annotations.  Since the annotations are a reflection of what's been shown in the literature, there may be conflicting studies.  More likely, this is a case of the GP up-regulating phagocytosis in some cases, and down-regulating it in other instances.  If you want to look into the annotation in depth, you can look into the specific paper: in this case it's 
https://europepmc.org/article/MED/26683154?singleResult=true

You may also want to look at the links on http://geneontology.org/docs/guide-go-evidence-codes/ to learn about the evidence codes.  It looks like GO:0050766 positive regulation of phagocytosis was based off Table 1, and there is a manual annotation from Mouse to support this GO: https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P08101&goId=GO:0050766

GO:0050765 negative regulation of phagocytosis is based on a statement referred to in this review, likely in the "FcγRIIB – inhibitory function" section. 

If, after reviewing the literature, you think there is an issue or incorrect annotation, please let us know (as well as the PMID of the literature which contradicts the annotation) and I will forward that to the team that made these annotations. '
