### ISSUE TITLE
automatic resolution of annotation disputes

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#26]
Annotation disputes are automatically resolved after 90 days with the message

If you are happy that the issue raised in your dispute has been addressed, then you need take no further action. If, however, the issue still stands,
then you should contact the group responsible for the annotation....

Can this be prevented?
The dispute should stay open until fixed....
Some fixes take more than a few months to filter through, this is just an additional administrative burden, as this is the only record of the issue.

(After closure the  entire thread disappears from view, the thread should really be accessible  for future reference , but this is another issue)

**Comment by kltm** [comment]
@ValWood 
I'm honestly not sure where discussion of GO policy should go, but I don't think the right eyes are on the helpdesk for this to have a clear course of action.
It might be better to get this onto one of the manager's boards...

**Comment by ValWood** [comment]
Will begin by asking Tony, (I can't assign tickets on this tracker)
@tonysawfordebi 
Normally I would mail Claire but I'm not sure who to ask now.

Can be escalated if Tony can't action it......

**Comment by tonysawfordebi** [comment]
As was explained in the email that was sent to all users of Protein2GO that announced that we were planning to implement this feature, we only auto-resolve disputes that concern annotations from external groups (i.e., those that don't use Protein2GO as their GO curation tool).

We don't store any information about external disputes in the database other than the details of when they were raised and by whom. In particular, there is no correspondence thread associated with them, because that relies on all parties involved having access to Protein2GO, which, by definition, external sources don't; the SOP for dealing with external disputes is to enter into a direct email exchange with the group responsible for the disputed annotation(s). So, in practice, the only thing that gets lost is the visibility of the dispute in Protein2GO, since a copy of the email that is sent to the external group notifying them of the dispute is also sent to the dispute initiator at the time when they raised it.

Just as a final point, we don't actually force anybody to use Protein2GO's dispute feature, which was only ever intended to be a fairly lightweight mechanism, and not a full-blown tracker, so if it's not appropriate for your particular use case, then by all means use GitHub or some other mechanism instead.

**Comment by ValWood** [comment]
I'm not a protein2GO user....I only use it for disputes. 

I think GitHub would be a better mechanism for disputes longer term. I'm finding them really difficult to track via protein2GO, so I'll use GitHub after the current batch.

Can anyone remind me where the GitHub ID look-up info  is kept?

val

**Comment by kltm** [comment]
@ValWood I'm not sure what you mean by the GitHub ID look-up info in this context.
Any user can see what theirs is by logging in, clicking on their icon in the far upper-right in the menu bar, and selecting "Your profile".
As far as other GO user metadata goes, that can be found here: https://github.com/geneontology/go-site/blob/master/metadata/users.yaml

**Comment by ValWood** [comment]
There is a  spreadsheet somewhere (created by @dosumis  I think) which provides the point of contact for each curating group?

**Comment by dosumis** [comment]
https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

**Comment by ValWood** [comment]
Thnaks @dosumis
