### ISSUE TITLE
how to pull all pathways with related genes? - new to geneontology 

### ISSUE THREAD

**Issue by radiodurans** [geneontology/helpdesk#261]
Hi I'm new to this database and was trying to find a way to get a dump of all of the pathways with unique identifiers/description of the pathway, and a list of genes contained within the pathway (where genes are represented using Entrez id format). Thanks.

**Comment by suzialeksander** [comment]
Hi @radiodurans, 

Thanks for contacting the GO Helpdesk.  If you're looking for pathways, a tool like BioCyc Pathways may be what you're looking for.  The Gene Ontology really deals with gene function.  Find general info about GO at http://geneontology.org/docs/faq/

If by "pathway" you mean the ontology, you can access the ontology files at http://geneontology.org/docs/download-ontology/ ; annotations can be accessed through http://geneontology.org/docs/download-go-annotations/

We also have GO-CAMs, and there is more information about those at https://geneontology.cloud/docs

If none of this is what you're asking about, please let me know.

**Comment by radiodurans** [comment]
Thank you what I'm looking for is some kind of way to associate the genes
mentioned in the gene ontology biological processes with their entrez id
codes. So I'd like a list of all GO BP for species Homo sapiens (for
example) with the entrez ids of the genes involved in that BP. I see how to
get the BP in Panther (all child ontologies of GO BP), but is there a way
to cross-reference the genes involved in each GO BP with entrez ids for
genes? For example, for mice genes I see that jax is able to make
associations between GO ids and entrez ids of genes:
http://www.informatics.jax.org/batch -- so I was curious how to link the
entrez ids to GO ids for all species, though I'm interested specifically in
Homo sapiens.

In addition, I saw it mentioned that you can query a monthly GO release as
well as a daily, updated DB as well. Are there  recommendations for when to
use the monthly over the daily or vice versa?

**Comment by suzialeksander** [comment]
Hi @radiodurans,

Most users should be using the official monthly releases.  The daily "snapshot" is mostly used by curators, who may need immediate access to annotations in order to continue their work.  There is a bit more QC checking done on the monthly releases than is done on the daily "snapshots", and all annotations changes (additions, deletions, edits) made over the previous period are included in the official release, so for most researchers the monthly release will be best. However, if you are working closely with a curation team and know a particular topic or paper of interest was just curated, you may wish to use Snapshot to ensure the most recent annotations are included in your analyses.

For the Entrez IDs, please see: 
http://geneontology.org/docs/faq/#how-do-i-find-the-annotations-mappings-for-entrez-ncbi-or-other-ids

If that doesn't sufficiently solve this issue, please let me know.
