### ISSUE TITLE
GO accession IDs for GO Molecular Function gene sets

### ISSUE THREAD

**Issue by vdhankani** [geneontology/helpdesk#27]
I'm trying to find GO accession IDs for all the gene sets in the GO Molecular Function category. It seems like a very straightforward query, but I've spent several hours on it trying GO ftp service, Amigo, Ensembl Biomart, all without success. Please suggest a solution.

**Comment by kltm** [comment]
@vdhankani 
Just to clarify what you're looking for here, for each of the ~800k gene products that have annotations to terms under `molecular_function`, for each one of those gene products, you want a complete list of all transitive and intransitive GO terms under `molecular_function` that it is associated with. Would that be a correct formulation of what you're looking for?

For AmiGO, while any one combination can be done easily, since it is backed by a document store, the particular grouping would be hard to create. As well, I suspect many online services might  timeout before completing or transferring such a query.

**Comment by kltm** [comment]
I think that command line tools might be the way to go here (assuming my formulation is correct). @cmungall can you think of anything for the transitive case? For intransitive, the GAFs plus a combination of grep/cut/sort/uniq would probably be fine.

**Comment by cmungall** [comment]
@vdhankani I think when you say 'gene sets' you mean ontology terms?

 1. Go to http://amigo.geneontology.org/amigo/search/ontology
 2. Under 'ontology source' select 'molecular function'. Total terms will drop to ~ 11k
 3. Click 'custom DL' (for download). You can customize the fields, but it sounds like the default 2 should work for your purposes
 4. Click 'download'

Let me know if I misunderstood your request
