### ISSUE TITLE
FTP problems

### ISSUE THREAD

**Issue by murphyte** [geneontology/helpdesk#282]
Hi GO -- we have a daily process monitoring for changes to GO annotations on your FTP site:
 ftp://ftp.geneontology.org/pub/go

We've been getting sporadic failures for the last week with downloading files, and generally slow performance. I can reproduce the problem in Chrome trying to retrieve that home directory. Do you know what the problem might be?

-Terence

**Comment by kltm** [comment]
@murphyte 

The FTP site is currently legacy and due to be decommissioned soon. Depending on your use case, if you are programmatically picking these up, you should be getting annotations from either http://current.geneontology.org/annotations or http://snapshot.geneontology.org/annotations , with the release date metadata like http://current.geneontology.org/metadata/release-date.json . We would recommend most users to use http://current.geneontology.org for the most up-to-date information.
Also see http://geneontology.org/docs/download-go-annotations/

**Comment by murphyte** [comment]
Thanks. We'll look at switching to a different data source.

**Comment by murphyte** [comment]
Hi @kltm  - we're not seeing a replacement for these three at http://current.geneontology.org/annotations/:
gene_association.GeneDB_Pfalciparum.gz
gene_association.gramene_oryza.gz
gene_association.jcvi.gz

Do you know what happened to those? Are they rolled into another file?

Thanks!

**Comment by kltm** [comment]
@murphyte 

I believe that those have been discontinued, probably due to lack of support from the upstream, but we could check back on the exact reasons if you're interested. Data on all currently supported upstreams can be found here: https://github.com/geneontology/go-site/tree/master/metadata/datasets

**Comment by murphyte** [comment]
I do see Plasmodium and Oryza data available in AmiGO:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Plasmodium%20falciparum%203D7%22&sfq=document_category:%22annotation%22
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Oryza%20sativa%20Japonica%20Group%22&sfq=document_category:%22annotation%22

Should everything in AmiGO be available in one of the FTP files? I'm wondering if they're buried in the giant UniProt file.

**Comment by kltm** [comment]
@murphyte That is likely what is going on here--the goa_uniprot file we load is essentially their standard GAF, filtered for IEAs and species that are already spoken for by another resource as the canonical source. In addition to that set, there are IBA annotations coming in from PAINT--annotations coming in from assertions using PANTHER trees. (As well as smaller sets from CACAO, etc.)
You can see the sources using the [Contributor] facet in AmiGO.

**Comment by davidbio** [comment]
Hi @kltm,
I am looking for the latest version of http://current.geneontology.org/annotations/goa_uniprot_all.gaf.gz
It looks like the specific organism GAFs were already updated to the latest 2021 build, but the UniProt link still returns the version from 2020.
Can you help with this?

**Comment by suzialeksander** [comment]
As of March, FTP was officially retired: https://github.com/geneontology/go-announcements/issues/202

If you need help replacing any specific files, please open a new ticket.
