### ISSUE TITLE
problems with decompress go assocdb-tables.tar.gz file

### ISSUE THREAD

**Issue by LujingF** [geneontology/helpdesk#29]
I have downloaded the latest go-assocdb-tables.tar.gz file for mysql, however, I found that it couldn't work when I use the command 'gunzip' or 'tar' to decompress this file. while I can use the 'tar' to decompress the termdb-tables.tar.gz. So, how I can fix this problems and any useful answers would be appreciated

**Comment by kltm** [comment]
@LujingF 
Could you provide a link to the file that you are having trouble with?

**Comment by LujingF** [comment]
well, here is the link http://archive.geneontology.org/latest-full/go_monthly-assocdb-tables.tar.gz

**Comment by kltm** [comment]
@LujingF 
Well, on Ubuntu 16.04, with 
```
bbop@wok:/tmp$ tar --version
tar (GNU tar) 1.28
```
and
```
bbop@wok:/tmp$ gunzip --version
gunzip (gzip) 1.6
```
the following worked:
```
wget http://archive.geneontology.org/latest-full/go_monthly-assocdb-tables.tar.gz
gunzip go_monthly-assocdb-tables.tar.gz
tar -xvf go_monthly-assocdb-tables.tar
```
Interestingly, the usual `tar -zxvf go_monthly-assocdb-tables.tar` reported
```
tar (child): Cannot connect to http: resolve failed

gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now
```
Odd that, I wonder if it has to do with file size...

**Comment by LujingF** [comment]
yeah, exactly! I have same problems. do you know which previous version is available for this go assocdb-tables data? maybe I can use the older version data for annotation

**Comment by kltm** [comment]
@LujingF 
The data can be decompressed just fine, just in a two step process as outlined above, so there is no need to use a different data set.
If you want to use a previous one, you can look at the contents of http://archive.geneontology.org and find the one that works best for you. Due to pipeline changes, there will be no further mysql dumps produced, in favor of switching to blazegraph as the primary query store; see this thread for a discussion: https://github.com/geneontology/helpdesk/issues/4

**Comment by LujingF** [comment]
@kltm I'm very appreciate for your help.
