### ISSUE TITLE
Database version

### ISSUE THREAD

**Issue by wcc-new** [geneontology/helpdesk#294]
Trinotate was used for annotation by using the cmd below:
$TRINOTATE_HOME/admin/Build_Trinotate_Boilerplate_SQLite_db.pl  Trinotate

I downloaded the data on 22 Nov 2020. 

May I know what is the version of the following database extracted that time? As I found out some of them had been updated 

1) my $GENE_ONTOLOGY_DAT_URL = "http://purl.obolibrary.org/obo/go/go-basic.obo";

2) May I know what is the version of the PFAM2GO downloaded on 22 Nov 2020 as well? 
if refer to "http://www.geneontology.org/external2go/pfam2go'  ; version date: version date: 2020/11/28
if refer to ftp://ftp.geneontology.org/pub/go/external2go/pfam2go; version date: version date: 2019/01/12
#my $PFAM2GO_DAT_URL = "http://www.geneontology.org/external2go/pfam2go"; # ftp://ftp.geneontology.org/pub/go/external2go/pfam2go

**Comment by suzialeksander** [comment]
The FTP site is currently legacy and due to be decommissioned soon. http://www.geneontology.org/external2go/pfam2go should redirect to http://current.geneontology.org/ontology/external2go/pfam2go  .  If you accessed current.geneontology.org via the URL you provided, you would get the date listed in the file in the newest release, not necessarily the one you accessed on 22 Nov. So, if you access current.geneontology.org today you'll see the January release.

We do not process the pfam2go file, so cannot guarantee the information in the headers is accurate, but if I look at http://release.geneontology.org/2020-11-17/ontology/external2go/pfam2go it lists `!version date: 2020/09/20 16:49:52` 

Depending on your use case, if you are programmatically picking these up, you should be getting external mapping files from either http://current.geneontology.org/ontology or http://snapshot.geneontology.org/ontology , with the release date metadata like http://current.geneontology.org/metadata/release-date.json . We would recommend most users to use http://current.geneontology.org for the most up-to-date information, but you can access all releases back to 2004-03-01 at http://release.geneontology.org/ .

Also see http://geneontology.org/docs/download-mappings/  

If you are not a developer with Trinotate or any other tool that uses GO, please let them (or any tool you use) know the ftp is no longer an appropriate source of files and that they are free to contact us for more information.
