### ISSUE TITLE
Why have some goa_human.gaf entries disappeared?

### ISSUE THREAD

**Issue by Emma-M-Rath** [geneontology/helpdesk#298]
Hi, At http://geneontology.org/ in "GO Enrichment Analysis", I had a statistically significant result in Oct 2020 for a list of genes, and I no longer have that result when I run the same list of genes in Feb 2021. I think it is because the 2020-09-10 goa_human.gaf.gz has entries for GO:0035904 entries for proteins LTBP1 and MYH10 (due to GO_REF:0000107, not due to a PMID) that are no longer present in the 2021-02-1 goa_human.gaf.gz. Why are these entries no longer present? How often do such impactful changes occur?

**Comment by suzialeksander** [comment]
Hi @Emma-M-Rath 

Thank you for contacting the GO Helpdesk.  I've looked at the 2020-09-10 release and found the following, which I think are what you were looking for in the most recent release:

UniProtKB	P35580	MYH10		GO:0035904	GO_REF:0000107	IEA	UniProtKB:Q61879|ensembl:ENSMUSP00000099671	P	Myosin-10	MYH10	protein	taxon:9606	20200714	Ensembl		

UniProtKB	Q14766	LTBP1		GO:0035904	GO_REF:0000107	IEA	UniProtKB:Q8CG19|ensembl:ENSMUSP00000001927	P	Latent-transforming growth factor beta-binding protein 1	LTBP1	protein	taxon:9606	20200714	Ensembl		


Since these are IEAs (see https://geneontology.github.io/docs/guide-go-evidence-codes/#electronic-annotation-evidence-code), please read https://geneontology.github.io/docs/faq/#sometimes-the-number-of-go-annotations-changes-significantly-over-a-short-period-of-time-why. 

If you don't think any of the reasons suggested in that FAQ apply or need more detailed information, please let me know.
