### ISSUE TITLE
FTP Access

### ISSUE THREAD

**Issue by weberle** [geneontology/helpdesk#300]
When I try to ftp from the ftp.geneontology.org/go/ontology-archive  site, it prompts me for a username (and will presumably prompt me for a password) - what is the username (and password) for this data?

**Comment by suzialeksander** [comment]
Hi @weberle 

Thanks for contacting the GO Helpdesk.  The FTP site is currently legacy and due to be decommissioned soon. Depending on your use case, if you are programmatically picking these up, you should be getting annotations from either http://current.geneontology.org/annotations or http://snapshot.geneontology.org/annotations , with the release date metadata like http://current.geneontology.org/metadata/release-date.json . We would recommend most users to use http://current.geneontology.org for the most up-to-date information.
Also see http://geneontology.org/docs/download-go-annotations/

**Comment by suzialeksander** [comment]
We have an official notice for retirement of these services: https://github.com/geneontology/go-announcements/issues/202
