### ISSUE TITLE
ontology release paths have changed, breaking third-party software

### ISSUE THREAD

**Issue by ppavlidis** [geneontology/helpdesk#302]
## Describe the issue/bug

It seems that until the last few days or so, the following url

http://release.geneontology.org/latest-termdb/go_daily-termdb.rdf-xml.gz 

and another that redirects there

http://archive.geneontology.org/latest-termdb/go_daily-termdb.rdf-xml.gz

were valid. 

This path is used in our software and it is breaking it for users and for students in a university course.  

I am unable to determine where this file can now be obtained. We can try to work around it, but it can be at least retained at the above location for a few months until we have time to fix our [software](https://erminej.msl.ubc.ca/), that would be great.

(If there was an announcement that this change was coming I didn't get it. ) Thanks for your help!

## Expected behavior

The URL should work.

## To Reproduce

Visit the URL.

## Screenshots

NA

**Comment by pgaudet** [comment]
@lpalbou Do you know what files @ppavlidis is looking for ? 
I dont think those were ever in the files we had in geneontology/release.

**Comment by ppavlidis** [comment]
Hi @pgaudet!

In addition I just noticed that the RDF-OWL files now provided at http://release.geneontology.org/ seem to have changed in some way and no longer work with our software. Is there a documented difference? The OBO files are fine.

**Comment by pgaudet** [comment]
Can you give an example of a file you usually download?

**Comment by ppavlidis** [comment]
An old one is in our codebase https://github.com/PavlidisLab/ermineJ/blob/master/src/test/data/go_daily-termdb.rdf-xml.zip

I've put what should be a more recent one  (11/2019) here: https://www.dropbox.com/s/05i1qrc30dedoqr/go_daily-termdb.rdf-xml.gz?dl=0

**Comment by kltm** [comment]
@ppavlidis My apologies for the troubles.

I believe this issue has probably come up since we finally powered down one of our legacy systems, affecting services/files that had been hosted on that machine (https://github.com/geneontology/go-announcements/issues/202). In this case, most of the files in question have likely not been updated in a couple of years as we have populated our new release system at release.geneontology.org (and current.geneontology.org). For more information on that, please see our documentation at http://geneontology.org/docs/go-archives/ .

As an immediate mitigation, likely the most recent file that we have archived for that data type (as part of the previous mysql build process) would be http://release.geneontology.org/2017-01-01/mysql_dumps/go_monthly-termdb.rdf-xml.gz . It seems that you may have access to a more recent one.

While we no longer provide a termdb.rdf-xml as part of our data products (as part of the cutover to a new data pipeline a couple of years ago), we still produce the data covering the previous products, but in a different form. If you could let us know what you were interested in, we may be able to help figure out the best way forward for you.

**Comment by ppavlidis** [comment]
Thanks for the quick information. Probably we can deprecate our support of the OWL format in favor of OBO (which we also support). At the same time I am curious what is different about the new RDF files from that old one, in case it is an easy fix, but we're not beholden to that format so it's not a big deal.

However, the other part of the issue is the loss of a consistent way to find the files. It would be really nice to have a "latest" symlink on your release site (and compressed files might be nice too). 

I realize you may be encouraging people to know what version they are using, which is good, but it means it is difficult for third party software to know the URI for a release (the dates don't look that predictable). The files self-document the release date in an attribute, as far as I know.

So it would be great if you have a fixed path to the latest go.owl.gz and go.obo.gz files. Thanks for considering (or pointing out where it is if I missed it!)

**Comment by ppavlidis** [comment]
Thanks Chris for the clarifications. And I forgot about http://geneontology.org/docs/download-ontology/.

I do understand that OWL is supported by GOC and didn't mean to imply otherwise, I was just confused about the relationships between the formats. Regardless, for our use, OBO is fine and we don't really need to add support for the latest RDF.

**Comment by pgaudet** [comment]
@ppavlidis So, can we close this, or do you need anything else ?
