### ISSUE TITLE
python code to extract _direct_ protein-protein interactions

### ISSUE THREAD

**Issue by urielsinger** [geneontology/helpdesk#32]
Hey,

Is there any easy way to extract **direct** (Homo sapiens) protein-protein interaction in python code?
I'm struggling as a beginner..

All I need in the columns: The two protein names, interaction type and PMID

Thank you!
Uriel

**Comment by kltm** [comment]
@cmungall Would you have anything for this?

**Comment by cmungall** [comment]
Hi there

Following on from #15 can I just clarify:

GO is not a protein-protein interaction database. GO is for describing the function of gene products. Sometimes that involves describing interaction partners of a gene to give more context for a function.

Are you interested in

 1. querying human protein-protein interaction data in general from a variety of sources (biogrid, intact, etc)?
 2. taking the subset of GO annotations that have protein-interaction data and extracting your fields from that. Note that for some species (including human) this may turn out to be similar to the results for 1, since some groups essentially include all IntAct PPIs in their GO annotations.

I can provide sample python code for either, although its only 2 that is within the scope of GO. If it truly is 2 that you're after, it may help to have more context about what you're trying to do, to make sure our advice doesn't lead you astray

**Comment by urielsinger** [comment]
Im interested in 1.

Furthermore, I'm not a biologist so I thought maybe I can extract from go someway direct interactions between proteins.
I would love a biological explaination why I was confused :)

**Comment by cmungall** [comment]
Yes, GO does include PPI annotations but it's not the primary purpose of GO. You may be better going to another database, or aggregating. I can provide some code that helps. But it may help to know more about your broader goals. You may also want to do a broader review of the landscape of PPI databases and evaluate which fit your needs best

**Comment by cmungall** [comment]
Here is an example of code to extract the binding partner information from a GO association file: https://github.com/geneontology/go-notebooks/blob/master/PPI_from_GAF.ipynb

**Comment by urielsinger** [comment]
Thank you for the great suggestions. It helped me a lot to understand what I need to do.
