### ISSUE TITLE
How to interpret terms with “positive” and “negative” specifiers

### ISSUE THREAD

**Issue by chriselhadi** [geneontology/helpdesk#321]
I am currently interpreting some GO terms I’ve clustered using binary clustering. The problem is that in every cluster, I get tens of terms having specifiers as “positive” and “negative regulation of …”. So I’m really confused and can’t decide how to interpret the results. What I did is the following: I ordered the terms according to their BH adjusted p values, and then decided to consider the specifier having the most significant p-value as ultimately describing the regulation of the cluster’s function… Is that the right way to do it? And what about the other specifier, should I just ignore its presence in favor of the more significant (e.g if the term “negative regulation of …” has the lowest pvalue, regardless if their is other “positive regulation of …” terms with higher and less significant pvalues, should I just assume the regulation is negative and ignore the positive terms?)? I also thought about counting the positive and negative terms and then take the specifier having the largest count as describing the cluster. Am i thinking right?

I attached a snapshot for clarity
![IMG_0403](https://user-images.githubusercontent.com/77117637/122535316-1dadcd00-d02c-11eb-8223-d85581079ae9.jpeg)

**Comment by RLovering** [comment]
Note that you need to consider the list of genes you are looking at. If this includes up and down regulated genes then I would suggest you consider the regulation terms more than the specific pos reg or neg reg terms because up regulation of a protein that positively regulates a process and down reg of a protein that neg regs that process will both lead to an increase that process. In addition, the role of a proteins in regulating a process will be determined by the cell or tissue type so this may mean some protein are involved in both positive and negative reg of a process, as is the case for the DUSP1 and IL6 which you have listed in the screen shot. This is why it is very important to also look at the proteins associated with the enriched term to get a sense of whether the enriched terms are being identified due to just a limited number of proteins and then use this information to decide which terms need to be selected and discussed in a publication/consideration of future research.

**Comment by lpalbou** [comment]
Agreed. Just an additional note: we have [over representation](http://pantherdb.org/tips/tips_overrep.jsp) test (small set of genes < 500) and enrichment test. You know if you can use enrichment test if 1) you have expression values for your gene set and 2) if you have enough genes (>1000). The interpretation of those two analysis also differs a little bit, including in the preparation of your gene set. 

As mentioned by @RLovering, if you are doing an [over representation](http://pantherdb.org/tips/tips_overrep.jsp) test and are including both the up and down regulated genes in your gene set, don't consider the "positive"/"negative" part of terms, it wouldn't be relevant. I usually just say that process X is "impaired". On the other hand, if you are separating the up & down gene sets, you say a bit more:

- For a set of down regulated genes: "positive regulation of X" means that pathway X will be less activated; inversely "negative regulation of X" means that pathway X will be less inhibited (so probably more activated than in your control)

- For a set of up regulated genes: "positive regulation of X" means pathway X is over activated (compared to your control) and "negative regulation of X" means pathway X is over inhibited (compared to your control)

If you did an enrichment with all your genes (eg from a transcriptomic experiment), it's a bit different, as you will have a sign indicating if the pathway is over or under expressed. The same logic as above then apply to interpret the positive/negative part of a term (eg under expression of a "negative regulation of X" means X will be less inhibited, etc).

More on that in this [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6519457/).

Hope that clarifies things a bit. Interpreting enrichment analysis can be tricky at times.
