### ISSUE TITLE
GO enrichment

### ISSUE THREAD

**Issue by sarabenm** [geneontology/helpdesk#33]
Hi,

I have a list of GO1 (associated to amino acid Sequences of interest) and a list of GO2  (associated to Subjects aligned to the sequences of interest by blastp).

There's no specific organism (either Eukaryota, either Bacteria)

Would there be a tool in order to compare the GO enrichment between the two GO sets or better  between each GO set and the background ? In order to see if one set is more enriched in regulatory networks, metabolism, ...

Thank you
Kind regards
PS: The equivalent would be a topGO analysis but for sure TopGO analysis is not possible to apply in our case. I don't start from gene lists. I start with GO lists (GO associated to amino-acid sequences  ).

**Comment by kltm** [comment]
@cmungall I don't think that any of our current tooling does this directly?

**Comment by cmungall** [comment]
@sarabenm I'm trying to frame your question in a way where we can make a statistically meaningful test, but am having trouble.

You could certainly do a enrichment test of a gene set `G` (your sequences of interest), using the whole genome as a background. You could also take all blast hits of all members of `G` in species `S`,  call this `G(S)` and do an enrichment test of this against all genes in `S`. You could also test `G` compared to `G(S)`.

However, it seems you already have your lists GO1 and GO2 (assume this is obtained by taking *all* annotations for `G` and `G(S)` respectively, rather than just the enriched annotations). I'm not sure what you can really do much other than just compare (e.g. intersection, differences).

Even here, I'm not sure how meaningful this is for many values of S. If S is not an experimental organism then many of the annotations will have been obtained by orthology or sequence similarity. So your answer may be more revealing about annotation process than biology.

What's the actual biological question you're trying to answer

**Comment by sarabenm** [comment]
Thank you for your answer
