### ISSUE TITLE
How to find all hormone receptors?

### ISSUE THREAD

**Issue by pengyu** [geneontology/helpdesk#41]
Are you aware of a complete list of hormone receptors?

It seems that GO does not have a term for all hormone receptors. (If so, should GO add such a GO term?)

The wiki page is incomplete.

https://en.wikipedia.org/wiki/Hormone_receptor

The following is a database of hormone receptors (the symbols are pasted below). But I am not sure how complete it is.

http://crdd.osdd.net/raghava/hmrbase/nphormone.php?table=recep&db=hmrbase&f_name=origin_org&f_value=Homo%20sapiens%20(Human)

Do you have any suggestions on where to find the complete list of
hormone receptors?

ADGRE1
ADGRE2
ADGRE3
ADRA1A
ADRA1B
ADRA1D
ADRA2A
ADRA2B
ADRA2C
ADRB1
ADRB2
ADRB3
AMHR2
AR
ATP6AP2
AVPR1A
AVPR1B
AVPR2
CALCR
CALCRL
CCKAR
CCKBR
CRHR1
CRHR2
CYSLTR1
CYSLTR2
ESR1
ESR2
ESRRA
ESRRB
ESRRG
FPR2
FSHR
GCGR
GHR
GHRHR
GHSR
GLP1R
GLP2R
GNRHR
GPR182
GPR50
GRPR
HNF4A
HNF4G
HTR1A
HTR1B
HTR1D
HTR1E
HTR1F
HTR2A
HTR2B
HTR2C
HTR3A
HTR4
HTR5A
HTR6
HTR7
INSR
LEPR
LEPROT
LEPROTL1
LHCGR
LTB4R
LTB4R2
MC1R
MC2R
MC3R
MC4R
MC5R
MCHR1
MCHR2
MLNR
MTNR1A
MTNR1B
NCOR2
NR0B1
NR0B2
NR1D1
NR1D2
NR1H2
NR1H3
NR1H4
NR1I2
NR1I3
NR2C1
NR2C2
NR2E1
NR2E3
NR2F1
NR2F2
NR2F6
NR3C1
NR3C2
NR4A1
NR4A2
NR4A3
NR5A1
NR5A2
NR6A1
OXER1
OXTR
PGR
POU1F1
PPARA
PPARD
PPARG
PRLHR
PRLR
PTGDR
PTGER1
PTGER2
PTGER3
PTGER4
PTGFR
PTGIR
PTH1R
PTH2R
RARA
RARB
RARG
RORA
RORB
RORC
RXFP1
RXFP2
RXFP3
RXFP4
RXRA
RXRB
RXRG
SCTR
SHBG
SSTR1
SSTR2
SSTR3
SSTR4
SSTR5
TBXA2R
THRA
THRB
TRHR
TSHR
VDR

**Comment by kltm** [comment]
@ukemi Sorry to bother, but if you have moment could you do a first pass triage?

**Comment by ukemi** [comment]
No problem @ktlm. I have been thinking about this for the past few days. I suspect that we do not have a distinct terms because of the issues of defining what a hormone is with respect to roles of molecules and the universality of how they act. The best way that I can think of to get the list would be to get the set of gene products annotated to 'hormone-receptor signaling pathway' or any of its children except the regulation terms. Then get the set of gene products annotated to 'receptor activity' and its children except the regulation terms. Then take the intersection of those two sets.
