### ISSUE TITLE
Document how to put PRO IDs in the GPI file

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#439]
**Please describe your question, idea, or concern.**

I wanted to do some Noctua curation using modified PRO forms, but these were not available for PomBAse because they are not currently in our GPI file.
It isn't clear from the GPI spec how to include these. Could you provide an example? @pgaudet mentioned that MGI have imported PRO IDs.

Thanks
Val

**Comment by deustp01** [comment]
@ukemi @nataled @vanaukenk I wonder if doing something in this direction, e.g., coining PRO IDs for all Alliance model organism proteins identified in the Reactome computationally projected pathways would be a reasonable chore for us / PRO and a good starting point for model organism GO-CAM curators?

**Comment by ValWood** [comment]
@vanaukenk  has added this to the GO agenda.

tagging @kltm

**Comment by ValWood** [comment]
tagging @kltm @krchristie

**Comment by deustp01** [comment]
> maybe even left to a second grant cycle.

Problwm - if you're thinking of the pathways2GO project, there will not be a second grant cycle. The original application was stuctured as a one-time project to clean up discrepancies and errors, to provide a harmonized, integrated view of material from Reactome, GO, PRO, Rhea to outside users, and to generate procedures, automated as much as possible, that the participating groups could use to maintain this harmonious state in the future. One explicit aim is to test the use of GO-CAMs derived from Reactome model organism pathways as templates for efficient expert annotation of model organism  biological processes, using PRO as the source of model organism protein identifiers, per the current GO-CAM standard.

**Comment by ukemi** [comment]
We do this for mouse proteoforms because we use them in models. Here are a few examples from our GPI file.

PR:Q19LI2	mA1BG	alpha-1B-glycoprotein (mouse)	mA1BG|alpha-1-B glycoprotein (mouse)	PR:000000001	NCBITaxon:10090	MGI:MGI:2152878			UniProtKB:Q19LI2	
PR:Q5YD48	mA1CF	APOBEC1 complementation factor (mouse)	mA1CF|APOBEC1-stimulating protein (mouse)	PR:000000001	NCBITaxon:10090	MGI:MGI:1917115			UniProtKB:Q5YD48	
PR:Q5YD48-1	mA1CF/iso:m1	APOBEC1 complementation factor isoform m1 (mouse)	mA1CF/iso:m1	PR:000000001	NCBITaxon:10090	MGI:MGI:1917115			UniProtKB:Q5YD48-1	
PR:Q5YD48-2	mA1CF/iso:m2	APOBEC1 complementation factor isoform m2 (mouse)	mA1CF/iso:m2	PR:000000001	NCBITaxon:10090	MGI:MGI:1917115			UniProtKB:Q5YD48-2	
PR:Q5YD48-3	mA1CF/iso:m3	APOBEC1 complementation factor isoform m3 (mouse)	mA1CF/iso:m3	PR:000000001	NCBITaxon:10090	MGI:MGI:1917115			UniProtKB:Q5YD48-3	
PR:000036218	mATP5ME/Ac:1	ATP synthase subunit e, mitochondrial acetylated 1 (mouse)	mATP5ME/Ac:1|UniProtKB:Q06185, Met-1, MOD:00058	PR:000000001	NCBITaxon:10090	MGI:MGI:106636

**Comment by ValWood** [comment]
I think this can close PRO IDs are there now.
