### ISSUE TITLE
fission yeast annotaions use 2 different species labels

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#468]
## Describe the issue/bug

In Amigo there are some IBA annotations to
Schizosaccharomyces pombe 972h-

## Expected behavior

All annotations should bet o

Schizosaccharomyces pombe

## To Reproduce

See AmiGO biological_proces and filter on "pombe"

Please include any information you can about: what, where, when, and why. Please include any URLs involved in the issue.

## Additional context

Add any other context about the issue that you feel may be important. E.g. browser version, time of day.

**Comment by kltm** [comment]
@pgaudet Is this "upstream" PAINT or to be tracked in our "pipeine" or "software essentials" projects? If the first, it may be good to consider a pseudo-project for it to improve PAINT-related tracking.

**Comment by pgaudet** [comment]
@ValWood 

I see for example [SPAC1F5.03c](https://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC1F5.03c), which is UniProt has the [Schizosaccharomyces pombe (strain 972 / ATCC 24843) (Fission yeast)](https://www.uniprot.org/taxonomy/284812) strain, see https://www.uniprot.org/uniprotkb/Q10058/entry

I think that would cause the wrong taxon ID to be imported?

**Comment by ValWood** [comment]
But it's the **same species** , this is 972, it's the **reference strain**, the same strain that I'm annotating.

This problem occurs because for a while NCBI created strain IDs, they don't do that anymore as far as I know,  but UniProt annotate to the strain ID [284812](https://www.uniprot.org/taxonomy/284812)
, and I annotate to the correct taxon  ID  4896, but these are *exactly* the same thing.
I don't know how it should be fixed but everything in GO which derives from the reference strain should be  species taxon taxon  ID  4896.

I realise for  some species with natural isolates which have different genome sequences it might be necessary to use the train info to differentiate strain specific variants, but this is the **same genome version**. The Swiss-Prot entries are all derived from the reference strain. 

I just don't know how to fix it. It seems that UniProt should map their annotation/entries to 4896 for GO?

**Comment by dustine32** [comment]
I looked into it a bit using example entry [PomBase:SPAC6G9.09c](https://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC6G9.09c). There are only 71 annotations to Schizosaccharomyces pombe 972h- (taxon:284812) in AmiGO so I think something special is happening to only a few pombe gene IBAs.

As we've discussed, all `paint_pombase.gaf` IBAs are coming into the GO release pipeline with strain `taxon:284812` because we just use the Reference Proteome taxon ID provided at the time we build the PANTHER library. This strain taxon 284812 is the taxon for every IBA in the final GO release `pombase.gaf`. However, it appears that most (all but 71) IBA annotations are displayed in AmiGO with their taxon IDs corrected to the species taxon 4896. @kltm might be able to confirm this but I suspect the GO pipeline-validated PomBase GPI is used to fill the organism column in AmiGO rather than the taxon column from the GAF annotation.

So, the issue I currently see for these 71 annotations is that their gene IDs were either not present in the upstream PomBase GPI or were, for some reason I have yet to debug, filtered out of the validated GPI. I'll keep taking a look at these.

**Comment by suzialeksander** [comment]
just bumping this for attention- if it would be better in /pipeline or something, let me know or feel free to move it

**Comment by kltm** [comment]
With @suzialeksander 
here (also https://github.com/geneontology/helpdesk/issues/468#issuecomment-1868164895): this needs a project and a priority.

**Comment by kltm** [comment]
AmiGO only loads GAFs, so no GPIs to worry about, technically speaking. AmiGO is easy to reason about as it is very simple at its core.
In general, the pipeline only cares about GAFs (give or take), with GPIs only entering the picture recently.
Noctua-derived annotations have an interesting story: going GPAD from minerva, then GAF output mediated by ontobio, mixed in with the rest of the sources for a given resource.
We'll also want to check our GPI handling, to see if we're actually making something or just passing through the upstream.

**Comment by kltm** [comment]
@dustine32 going to reach out on the PAINT side and will come back with more info.

**Comment by pgaudet** [comment]
AmiGO 

<img width="521" alt="image" src="https://github.com/geneontology/helpdesk/assets/4782928/40a0bdd8-2f80-4b45-948c-97d3e108d55a">



AmiGO current (ie the upcoming release) 

<img width="482" alt="image" src="https://github.com/geneontology/helpdesk/assets/4782928/57f29d3c-80cc-4ec4-8e13-7f2f5fd9f3c0">

**Comment by dustine32** [comment]
@pgaudet Thanks for checking! I'm pretty certain the strain taxon for those 66 annotations is no longer coming from the IBA GAFs as I double-checked the upstream files that have been in place since 2024-04-09 and there are no `taxon:284812` lines.

@kltm Perhaps there is a cached file in AmiGO pulling this taxon data for these gene products, which at some point derived this taxon from our older IBA GAFs?

**Comment by kltm** [comment]
@dustine32 I believe that @pgaudet was trying to show the fix here, but got screenshots mixed up.

Search for `pom` in the species fileters at 

https://amigo-staging.geneontology.io/amigo/search/annotation
```
Schizosaccharomyces pombe	(52123)
```

vs

https://amigo.geneontology.org/amigo/search/annotation
```
Schizosaccharomyces pombe	(53501)
Schizosaccharomyces pombe 972h-	(66)
```

**Comment by dustine32** [comment]
@kltm Oh thank you thank you!!

**Comment by pgaudet** [comment]
AmiGO now looks fine 

<img width="519" alt="image" src="https://github.com/geneontology/helpdesk/assets/4782928/60b75501-ef40-42c6-a915-b3d8dbdc326a">
