### ISSUE TITLE
adjuted P-values are all 1 

### ISSUE THREAD

**Issue by RobertWBaldwin** [geneontology/helpdesk#49]
Hi,

When using GP enrichment analysis I used a set of ExAC constrained genes as my reference set (~10100) and looked for enrichments in my input set of ~500 genes. I got a lot of enrichments > 2 but all my p-values after correction for multiple testing were 1. If there were three genes in the ref set that map to a process and you get all 3 of those in the input set the adjusted p-value will be 1, even though the expected number of genes was 0.1 or something, like and 18 fold enrichment. I'm wondering if this is just not the right kind of test? Or just use all genes in the genome as the ref set because then I get enrichments after corection ofr multuple testing. 

Thanks

**Comment by thomaspd** [comment]
This is probably expected behavior, as the test is behaving properly on our standard validation sets.  But just to look more closely, you can try unchecking the box that selects the Bonferroni correction, and re-run the analysis.  You should see the unadjusted P-values then, and these should not be all 1 (and you can even check the unadjusted P value using an online binomial test).  But if you still have questions, send an email to feedback@pantherdb.org, and attach the files you're uploading, and we can troubleshoot.

**Comment by RobertWBaldwin** [comment]
Yes the unadjusted p-values are all there and not 0. I was using the correction for multiple testing. What good are unadjusted p-values? The problems is that if for some process 3 genes are in the refg set and I see all 3 in the input set that is not significant after correction. In short, it was logically impossible, no matter what genes occured in the input set, to get a significant p-value. Hence my question: is this the right kind of test to do? I mean are there other options. The problem with using all genes in the genome as a ref set is that my analysis only considered genes showing functional constraint in ExAC so that introduces some bias since this set of genes will have a larger proprotion of brain expressed/devleopmetnal genes. I just wanted to show that my enrichments were did not result from this kidn of circular logic whereby you select for brain related genes and then report enrichment for brain related terms.

**Comment by kltm** [comment]
@thomaspd Is there any more action for this item, or should be change to a different tracker for this?

**Comment by thomaspd** [comment]
I agree this sounds strange, but there's not much more we can do to troubleshoot without trying your input (and reference) sets ourselves.  You can send them to the panther feedback email above if you'd like to try that.  But we will be releasing a new default test in the next couple of days, that uses the FDR to control for multiple testing instead of Bonferroni.  This will be less conservative.
