### ISSUE TITLE
causally upstream or within annotations transferred by the Ensembl pipline become part_of

### ISSUE THREAD

**Issue by ValWood** [geneontology/helpdesk#505]
## Describe the issue/bug

UniProtKB:Q8K0Z7 Taco1 acts_upstream_of_or_within GO:0033617    mitochondrial cytochrome c oxidase assembly
ECO:0000315   IMP PMID:27319982 MGI:MGI:5905291 10090 Mus musculus
MGIoccurs_in (EMAPA:16105) more...

This  is transferred to human, and becomes an involved_in annotation

<img width="1301" alt="Screenshot 2024-10-24 at 17 41 59" src="https://github.com/user-attachments/assets/62e7ca82-f333-4715-8722-10a564aa880c">

## Additional context

Annotations that are not  involved_in should (presumably) not be transferred  at all (even with the correct relation). 

In this case,  Taco1 does act upstream of " mitochondrial cytochrome c oxidase assembly" it's a mitochondrial translation regulatory factor.

**Comment by suzialeksander** [comment]
@pgaudet

**Comment by pgaudet** [comment]
Thanks for reporting this. I'll discuss this with @alexsign .

**Comment by pgaudet** [comment]
Alex has implemented the default relations as described in [GORULE-0000061](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000061.md) and use 'acts upstream of or within' 

This will be implemented in the next GOA release.

**Comment by ValWood** [comment]
So the annotations will still be transferred?

**Comment by pgaudet** [comment]
Yes - unless we can come up with rules of what should and should not be transferred. 

You are proposing to shut down the Ensembl pipeline, right?

**Comment by ValWood** [comment]
No, just to not transfer "causally upstream" annotation (even if preserving the causally upstream relation). 
Only transfer part_of. There will still be a lot of dodgy transfer, but it would limit it somewhat.

**Comment by hattrill** [comment]
@pgaudet @ValWood  Sorry, I didn't pay enough attention to this ticket. I think this is wrong. Val was suggesting that annotations with acts upstream of or within should not be propagated via the ENSEMBL pipeline, I think, but I don't think that the other electronic pipelines were in scope.
The result of this change is that all the IEAs from InterPro2GO and Rfam2GO are getting a RO:0002264 acts upstream of or within rather than an RO:0002331 involved in - this was the intended purpose.
