### ISSUE TITLE
assocdb not available in obo format

### ISSUE THREAD

**Issue by fochtmanb** [geneontology/helpdesk#59]
the lead database guide says that assocdb should be available in obo format
( http://geneontology.org/page/lead-database-guide )
however, this is not available in latest-lite or latest-full, will this file be made available soon?

**Comment by kltm** [comment]
@fochtmanb 
Our apologies--that appears to be an error in the documentation. Doing a quick sampling back in time, it appears that the OBO XML version of the assocdb has not been produced for at least five years.
At this point, due to the current pipeline being EOLed (see https://github.com/geneontology/helpdesk/issues/4), we are unlikely to start producing that file. In fact, many of these files will no longer be produced. We will try and current documentation as we switch over to our new system.

-termdb.obo-xml.gz
