### ISSUE TITLE
Can we set up automatic reminder of tickets assigned to the assigne (s)? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/helpdesk#78]
From https://github.com/geneontology/go-annotation/issues/1388

We all need a way to be reminded which tickets are assigned to us!

Can this be done in some sort of "git hub" management mode (i.e select all tickets and send a message saying "you are the assignee of this ticket, please check if it can be closed").... A monthly alert......I will never look otherwise.... I think this would get a lot of GitHub tickets "unstuck"

At least for the go-ontology and go-annotation repos that would be really nice. 

Thanks, Pascale

**Comment by kltm** [comment]
For myself:
https://github.com/geneontology/go-annotation/issues/assigned/kltm

People hopefully have GitHub setup to receive emails when they are assigned or mention on a ticket, meaning that it would be up to them to use their email folders on their client to make that useful. Otherwise, GitHub provides no direct support besides making it trivial to click a link and see what is assigned--there is no "management mode". Options would be bespoke software or getting a plugin. However, I think it would be worthwhile is people just periodically looked at the tickets assigned to themselves in the various trackers.

**Comment by kltm** [comment]
Any thoughts on this @cmungall ?
