### ISSUE TITLE
Find (MolecularFunction)--Part_of--(BiologicalProcess) link

### ISSUE THREAD

**Issue by StefanHaunsberger** [geneontology/helpdesk#93]
Hi,
I am currently working with a local GO MySQL instance and try to find all asserted links in GO.

### Challenge
I'm trying to find the link between (GO:0044183)--Part_of-->(GO:0006457), where 'GO:0044183' is from the molecular function domain and GO:0006457 is from the biological process domain (see [Ancestor Chart](https://www.ebi.ac.uk/QuickGO/term/GO:0044183#ancestorChart)), in my local GO-MySQL instance.

### Setup
1. Downloaded go_weekly-termdb-tables.tar.gz from [GeneOntology-FTP](http://bit.ly/2rz7wcd)
2. Created a local MySQL instance of the GO database
3. Querying for the child-GO-term 'GO:0044183' to find all its links to other GO-terms using
```SQL
SELECT
 child.term_type AS ontology,
 child.acc AS childId,
 rel.acc AS relationship,
 parent.acc AS parentId
FROM
 term AS child
 INNER JOIN term2term ON (child.id=term2_id)
 INNER JOIN term AS parent ON (parent.id=term1_id)
 INNER JOIN term AS rel ON (rel.id=relationship_type_id)
WHERE child.acc = 'GO:0044183';
```
4. Only 'GO:0005515' from the molecular function domain is included in the result set, but unfortunately 'GO:0048308' is not included.
![image](https://user-images.githubusercontent.com/5872625/35342936-4907b8c2-0121-11e8-8ccf-45763fe266c1.png)

I'm wondering if there is a different way to receive the part_of inter-domain connections?

Best Regards,

Stefan

**Comment by kltm** [comment]
@StefanHaunsberger 

First, and most importantly, I would direct you to this item in another thread to give you the context of the current state/status of the legacy MySQL dumps:

https://github.com/geneontology/helpdesk/issues/4#issuecomment-290152458

If using the legacy database dump, I would also direct you to the schema documentation and example queries:

http://geneontology.org/page/lead-database-guide#schema
http://wiki.geneontology.org/index.php/Example_LEAD_Queries

Given that, the graph_path table was typically the most common way of understanding the relation between two terms.

http://geneontology.org/page/lead-database-schema-views#go-optimisations.table.graph-path

**Comment by StefanHaunsberger** [comment]
@kltm Thanks for your reply and suggestions.

I've read through the graph-path table description, checked out the database schema and the query I initially used to find my results were actually from the Example_LEAD_Queries. 

When I run the following query, which should return all ancestors, regarding the documentation it again only returns the ones that are within the same domain molecular function.
#### Query
(Query taken from [Example_LEAD_Queries](http://wiki.geneontology.org/index.php/Example_LEAD_Queries#Find_ancestors_of_the_node_.27nucleus.27))
```sql
SELECT DISTINCT
        ancestor.*, 
        graph_path.distance,
        graph_path.term1_id AS ancestor_id
 FROM 
  term
  INNER JOIN graph_path ON (term.id=graph_path.term2_id)
  INNER JOIN term AS ancestor ON (ancestor.id=graph_path.term1_id)
 WHERE term.acc = 'GO:0044183';
```
#### Output
![image](https://user-images.githubusercontent.com/5872625/35379691-cb586c8a-01ae-11e8-8d2b-433b4810d4dc.png)

Thanks for your help.

Kind Regards,

Stefan

**Comment by cmungall** [comment]
Hi Stefan,

Historically the MySQL database has only been loaded with what we call go-basic. This is explained here:

http://geneontology.org/page/download-ontology

go-basic *intentionally* omits relationships that span the 3 branches of GO. This is because there are a large number of applications that use the GO (either via the MySQL database, or direct use of the ontology files) initially made assumptions that this was the case, and broke otherwise.

However, I think that it may be time to revise this assumption. There is still a need for a go-basic that omits relationship types that shouldn't be traversed for gene propagation. However, the historic need to strictly partition the 3 hierarchies may no longer hold and we should remove it. Undoubtedly some software will break, but this may be the only way to shift forward (after giving sufficient notice).

This doesn't help you in the short term. Do you need to do this in MySQL, would an alternate API, a programmatic lib (e.g python) or a one-off export help you?

**Comment by StefanHaunsberger** [comment]
Hi Chris,

Thanks for the detailed answer.
In this case, I've decided to stick with the go-basic version.

Thanks again and kind regards,

Stefan
